### ISSUE TITLE
New Ditmars release?

### ISSUE THREAD

**Issue by picaron** [spring-cloud/spring-cloud-stream-starters#50]
Hi @sobychacko !

I was wondering, is there a new Ditmars release planned soon? 

We'd like to use the Spring Cloud Stream starter with spring-amqp 1.7.9 which supports auto-recovery.

Thanks in advance!

**Comment by sobychacko** [comment]
Hi @picaron,  Currently there is no service release planned for Ditmars. The latest Rabbit binder in Ditmarts (1.3.3), brings Spring Boot 1.5.7 that brings spring-amqp 1.7.4.  You should be able to override the boot dependency or spring-amqp dependency in the application in order to use this feature. Did you try upgrading and encounter issues?

**Comment by picaron** [comment]
Ok thanks for the info @sobychacko 👍
